# Generated by Django 5.0.1 on 2024-02-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
    ]
